### ISSUE TITLE
Project Todo List

### ISSUE THREAD

**Issue by wavybangsy** [Glinary/RestaurantReviewWebApp#6]
⭐️ REVIEW
- [x] Expandable Review
- [x] helpful/unhelpful reaction (w/ count)
- [x] rating menu (stars system or recommended/not recommended)
- [x] delete option for user review
- [x] edit option for user review (w/ “edited” indication if edited)
- [x] fix navbar (pwede icopy paste yung sa index.html

⭐️ REGISTRATION
- [x] add  “add avatar” in layout

⭐️ LOGIN 
- [x] add “remember me” box

⭐️ MAIN APP
- [x] Logout button in menu

⭐️ SEARCH RESULT PAGE
- [x] add filter option
    - by overall rating

⭐️ ESTABLISHMENT OWNER RESPONSE
- [x] account for owners
- [x] response to reviews

🚩🚩🚩🚩🚩🚩 NO PAGES YET 🚩🚩🚩🚩🚩🚩
- [x] Restaurant Establishment Page
- [x] Restaurant Establishment Page (with resto reply)
- [x] Edit User Info Page
- [x] Search Result Page

**Comment by wavybangsy** [comment]
IMPROVEMENT:


⭐️ LOGIN PAGE
- [x] dynamic login page

⭐️ INDEX:
- [x]  gawing dynamic ung navbar ng index.html (nagawa ko na yung ideal navbar sa viewprofile)
- [x] ayusin yung alignment ng profile pic sa navbar cuz hindi dynamic
- [x] iimplement yung hover view sa index.html


⭐️ VIEW PROFILE
- [x] padagdag nung blue rectangles sa sides para sa viewprofile for desktop view

⭐️ RESTAURANT
- [x] hovering of each box in Desktop Restaurant

⭐️ REVIEW PAGE:
- [x] make Review Page responsive

⭐️ REVIEW BOXES
- [x]  Star images in User Review boxes
- [ ] may navigator sana yung sa user reviews (napipindot yung page 1,2,3,4) pero if di na kaya idisplay nalang lahat ng reviews sa page

⭐️ SYNC NAVBARS
- [x] Index logged out
- [x] Index logged in
- [x] Restaurant Grid view logged in
- [x] Restaurant Grid logged out
- [x] Search Page logged in
- [x] Search Page logged out
- [x] Restaurant Page logged in
- [x] Restaurant Page logged out
- [x] Add Review Page logged in
- [x] Edit Profile Page logged in

⭐️ SYNC RESTO CONTAINER GRID
- [x] Index logged in
- [x] Index logged out
- [x] Restaurant  Grid View logged in
- [x] Restaurant Grid View logged out

⭐️ IMPORTANT CHECKS
- [ ] Overall Responsiveness
- [ ] Polished Layout
- [x] Contents 
- [x] Connected pages

🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩  NOT YET RESPONSIVE:  🚩🚩🚩🚩🚩🚩🚩🚩🚩🚩
- [x] ALL view user profiles
- [x] Review Page

**Comment by EmGZ** [comment]
⭐️ HOME PAGE

- [x] Make it Dynamic for all views (Tablet, PC, CP)
- [x] Add Contents for the Restaurants
- [x] Slider
- [x] hover/ unhover

**Comment by EmGZ** [comment]
⭐️ MCO1 MUST DO SPECS

- [x] 5 Users
- [x] 5 Posts
- [x] 5 Comments

**Comment by wavybangsy** [comment]
- [x] Make resto page (refer to figma "Desktop Restaurant (clicked from view all)"
- [x] fix mobile/tablet view of index.html (ayaw magscroll down)
- [x] Change navbar for desktop view
- [x] Fix hover issue sa index.html (di ko maayos cuz di ko maview on my end)
- [x] properly link all sites
- [x] navbar bug hover
- [x] dimensions problem (long height):
-  - [x] review page 
-  - [x] index
-  - [x] login page
-  - [x] registration page
-  - [x] restaurant
