### ISSUE TITLE
Caution for Phase 2

### ISSUE THREAD

**Issue by Glinary** [Glinary/RestaurantReviewWebApp#8]
- [x] Few text in description may affect the layout. Consider setting a min-width for the establishment description.
- [x] review boxes text needs to be maxed for pictures to flush right. Consider specifying max width for text portion so it won't affect pictures section
- [x] image layout may be messed up if review text is not long enough.
- [x] show no reviews interface if there are no reviews

**Comment by wavybangsy** [comment]
**TODO LIST FOR PHASE 2**

Additions:
- [ ] Add the address for each restaurant
- [ ] Add contact number
- [ ] Add opening hours
- [ ] Add cuisine
